// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module multiplier_multiplier_Pipeline_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sysarrayC_63_out,
        sysarrayC_63_out_ap_vld,
        sysarrayC_62_out,
        sysarrayC_62_out_ap_vld,
        sysarrayC_61_out,
        sysarrayC_61_out_ap_vld,
        sysarrayC_60_out,
        sysarrayC_60_out_ap_vld,
        sysarrayC_59_out,
        sysarrayC_59_out_ap_vld,
        sysarrayC_58_out,
        sysarrayC_58_out_ap_vld,
        sysarrayC_57_out,
        sysarrayC_57_out_ap_vld,
        sysarrayC_56_out,
        sysarrayC_56_out_ap_vld,
        sysarrayC_55_out,
        sysarrayC_55_out_ap_vld,
        sysarrayC_54_out,
        sysarrayC_54_out_ap_vld,
        sysarrayC_53_out,
        sysarrayC_53_out_ap_vld,
        sysarrayC_52_out,
        sysarrayC_52_out_ap_vld,
        sysarrayC_51_out,
        sysarrayC_51_out_ap_vld,
        sysarrayC_50_out,
        sysarrayC_50_out_ap_vld,
        sysarrayC_49_out,
        sysarrayC_49_out_ap_vld,
        sysarrayC_48_out,
        sysarrayC_48_out_ap_vld,
        sysarrayC_47_out,
        sysarrayC_47_out_ap_vld,
        sysarrayC_46_out,
        sysarrayC_46_out_ap_vld,
        sysarrayC_45_out,
        sysarrayC_45_out_ap_vld,
        sysarrayC_44_out,
        sysarrayC_44_out_ap_vld,
        sysarrayC_43_out,
        sysarrayC_43_out_ap_vld,
        sysarrayC_42_out,
        sysarrayC_42_out_ap_vld,
        sysarrayC_41_out,
        sysarrayC_41_out_ap_vld,
        sysarrayC_40_out,
        sysarrayC_40_out_ap_vld,
        sysarrayC_39_out,
        sysarrayC_39_out_ap_vld,
        sysarrayC_38_out,
        sysarrayC_38_out_ap_vld,
        sysarrayC_37_out,
        sysarrayC_37_out_ap_vld,
        sysarrayC_36_out,
        sysarrayC_36_out_ap_vld,
        sysarrayC_35_out,
        sysarrayC_35_out_ap_vld,
        sysarrayC_34_out,
        sysarrayC_34_out_ap_vld,
        sysarrayC_33_out,
        sysarrayC_33_out_ap_vld,
        sysarrayC_32_out,
        sysarrayC_32_out_ap_vld,
        sysarrayC_31_out,
        sysarrayC_31_out_ap_vld,
        sysarrayC_30_out,
        sysarrayC_30_out_ap_vld,
        sysarrayC_29_out,
        sysarrayC_29_out_ap_vld,
        sysarrayC_28_out,
        sysarrayC_28_out_ap_vld,
        sysarrayC_27_out,
        sysarrayC_27_out_ap_vld,
        sysarrayC_26_out,
        sysarrayC_26_out_ap_vld,
        sysarrayC_25_out,
        sysarrayC_25_out_ap_vld,
        sysarrayC_24_out,
        sysarrayC_24_out_ap_vld,
        sysarrayC_23_out,
        sysarrayC_23_out_ap_vld,
        sysarrayC_22_out,
        sysarrayC_22_out_ap_vld,
        sysarrayC_21_out,
        sysarrayC_21_out_ap_vld,
        sysarrayC_20_out,
        sysarrayC_20_out_ap_vld,
        sysarrayC_19_out,
        sysarrayC_19_out_ap_vld,
        sysarrayC_18_out,
        sysarrayC_18_out_ap_vld,
        sysarrayC_17_out,
        sysarrayC_17_out_ap_vld,
        sysarrayC_16_out,
        sysarrayC_16_out_ap_vld,
        sysarrayC_15_out,
        sysarrayC_15_out_ap_vld,
        sysarrayC_14_out,
        sysarrayC_14_out_ap_vld,
        sysarrayC_13_out,
        sysarrayC_13_out_ap_vld,
        sysarrayC_12_out,
        sysarrayC_12_out_ap_vld,
        sysarrayC_11_out,
        sysarrayC_11_out_ap_vld,
        sysarrayC_10_out,
        sysarrayC_10_out_ap_vld,
        sysarrayC_9_out,
        sysarrayC_9_out_ap_vld,
        sysarrayC_8_out,
        sysarrayC_8_out_ap_vld,
        sysarrayC_7_out,
        sysarrayC_7_out_ap_vld,
        sysarrayC_6_out,
        sysarrayC_6_out_ap_vld,
        sysarrayC_5_out,
        sysarrayC_5_out_ap_vld,
        sysarrayC_4_out,
        sysarrayC_4_out_ap_vld,
        sysarrayC_3_out,
        sysarrayC_3_out_ap_vld,
        sysarrayC_2_out,
        sysarrayC_2_out_ap_vld,
        sysarrayC_1_out,
        sysarrayC_1_out_ap_vld,
        sysarrayC_out,
        sysarrayC_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] sysarrayC_63_out;
output   sysarrayC_63_out_ap_vld;
output  [31:0] sysarrayC_62_out;
output   sysarrayC_62_out_ap_vld;
output  [31:0] sysarrayC_61_out;
output   sysarrayC_61_out_ap_vld;
output  [31:0] sysarrayC_60_out;
output   sysarrayC_60_out_ap_vld;
output  [31:0] sysarrayC_59_out;
output   sysarrayC_59_out_ap_vld;
output  [31:0] sysarrayC_58_out;
output   sysarrayC_58_out_ap_vld;
output  [31:0] sysarrayC_57_out;
output   sysarrayC_57_out_ap_vld;
output  [31:0] sysarrayC_56_out;
output   sysarrayC_56_out_ap_vld;
output  [31:0] sysarrayC_55_out;
output   sysarrayC_55_out_ap_vld;
output  [31:0] sysarrayC_54_out;
output   sysarrayC_54_out_ap_vld;
output  [31:0] sysarrayC_53_out;
output   sysarrayC_53_out_ap_vld;
output  [31:0] sysarrayC_52_out;
output   sysarrayC_52_out_ap_vld;
output  [31:0] sysarrayC_51_out;
output   sysarrayC_51_out_ap_vld;
output  [31:0] sysarrayC_50_out;
output   sysarrayC_50_out_ap_vld;
output  [31:0] sysarrayC_49_out;
output   sysarrayC_49_out_ap_vld;
output  [31:0] sysarrayC_48_out;
output   sysarrayC_48_out_ap_vld;
output  [31:0] sysarrayC_47_out;
output   sysarrayC_47_out_ap_vld;
output  [31:0] sysarrayC_46_out;
output   sysarrayC_46_out_ap_vld;
output  [31:0] sysarrayC_45_out;
output   sysarrayC_45_out_ap_vld;
output  [31:0] sysarrayC_44_out;
output   sysarrayC_44_out_ap_vld;
output  [31:0] sysarrayC_43_out;
output   sysarrayC_43_out_ap_vld;
output  [31:0] sysarrayC_42_out;
output   sysarrayC_42_out_ap_vld;
output  [31:0] sysarrayC_41_out;
output   sysarrayC_41_out_ap_vld;
output  [31:0] sysarrayC_40_out;
output   sysarrayC_40_out_ap_vld;
output  [31:0] sysarrayC_39_out;
output   sysarrayC_39_out_ap_vld;
output  [31:0] sysarrayC_38_out;
output   sysarrayC_38_out_ap_vld;
output  [31:0] sysarrayC_37_out;
output   sysarrayC_37_out_ap_vld;
output  [31:0] sysarrayC_36_out;
output   sysarrayC_36_out_ap_vld;
output  [31:0] sysarrayC_35_out;
output   sysarrayC_35_out_ap_vld;
output  [31:0] sysarrayC_34_out;
output   sysarrayC_34_out_ap_vld;
output  [31:0] sysarrayC_33_out;
output   sysarrayC_33_out_ap_vld;
output  [31:0] sysarrayC_32_out;
output   sysarrayC_32_out_ap_vld;
output  [31:0] sysarrayC_31_out;
output   sysarrayC_31_out_ap_vld;
output  [31:0] sysarrayC_30_out;
output   sysarrayC_30_out_ap_vld;
output  [31:0] sysarrayC_29_out;
output   sysarrayC_29_out_ap_vld;
output  [31:0] sysarrayC_28_out;
output   sysarrayC_28_out_ap_vld;
output  [31:0] sysarrayC_27_out;
output   sysarrayC_27_out_ap_vld;
output  [31:0] sysarrayC_26_out;
output   sysarrayC_26_out_ap_vld;
output  [31:0] sysarrayC_25_out;
output   sysarrayC_25_out_ap_vld;
output  [31:0] sysarrayC_24_out;
output   sysarrayC_24_out_ap_vld;
output  [31:0] sysarrayC_23_out;
output   sysarrayC_23_out_ap_vld;
output  [31:0] sysarrayC_22_out;
output   sysarrayC_22_out_ap_vld;
output  [31:0] sysarrayC_21_out;
output   sysarrayC_21_out_ap_vld;
output  [31:0] sysarrayC_20_out;
output   sysarrayC_20_out_ap_vld;
output  [31:0] sysarrayC_19_out;
output   sysarrayC_19_out_ap_vld;
output  [31:0] sysarrayC_18_out;
output   sysarrayC_18_out_ap_vld;
output  [31:0] sysarrayC_17_out;
output   sysarrayC_17_out_ap_vld;
output  [31:0] sysarrayC_16_out;
output   sysarrayC_16_out_ap_vld;
output  [31:0] sysarrayC_15_out;
output   sysarrayC_15_out_ap_vld;
output  [31:0] sysarrayC_14_out;
output   sysarrayC_14_out_ap_vld;
output  [31:0] sysarrayC_13_out;
output   sysarrayC_13_out_ap_vld;
output  [31:0] sysarrayC_12_out;
output   sysarrayC_12_out_ap_vld;
output  [31:0] sysarrayC_11_out;
output   sysarrayC_11_out_ap_vld;
output  [31:0] sysarrayC_10_out;
output   sysarrayC_10_out_ap_vld;
output  [31:0] sysarrayC_9_out;
output   sysarrayC_9_out_ap_vld;
output  [31:0] sysarrayC_8_out;
output   sysarrayC_8_out_ap_vld;
output  [31:0] sysarrayC_7_out;
output   sysarrayC_7_out_ap_vld;
output  [31:0] sysarrayC_6_out;
output   sysarrayC_6_out_ap_vld;
output  [31:0] sysarrayC_5_out;
output   sysarrayC_5_out_ap_vld;
output  [31:0] sysarrayC_4_out;
output   sysarrayC_4_out_ap_vld;
output  [31:0] sysarrayC_3_out;
output   sysarrayC_3_out_ap_vld;
output  [31:0] sysarrayC_2_out;
output   sysarrayC_2_out_ap_vld;
output  [31:0] sysarrayC_1_out;
output   sysarrayC_1_out_ap_vld;
output  [31:0] sysarrayC_out;
output   sysarrayC_out_ap_vld;

reg ap_idle;
reg sysarrayC_63_out_ap_vld;
reg sysarrayC_62_out_ap_vld;
reg sysarrayC_61_out_ap_vld;
reg sysarrayC_60_out_ap_vld;
reg sysarrayC_59_out_ap_vld;
reg sysarrayC_58_out_ap_vld;
reg sysarrayC_57_out_ap_vld;
reg sysarrayC_56_out_ap_vld;
reg sysarrayC_55_out_ap_vld;
reg sysarrayC_54_out_ap_vld;
reg sysarrayC_53_out_ap_vld;
reg sysarrayC_52_out_ap_vld;
reg sysarrayC_51_out_ap_vld;
reg sysarrayC_50_out_ap_vld;
reg sysarrayC_49_out_ap_vld;
reg sysarrayC_48_out_ap_vld;
reg sysarrayC_47_out_ap_vld;
reg sysarrayC_46_out_ap_vld;
reg sysarrayC_45_out_ap_vld;
reg sysarrayC_44_out_ap_vld;
reg sysarrayC_43_out_ap_vld;
reg sysarrayC_42_out_ap_vld;
reg sysarrayC_41_out_ap_vld;
reg sysarrayC_40_out_ap_vld;
reg sysarrayC_39_out_ap_vld;
reg sysarrayC_38_out_ap_vld;
reg sysarrayC_37_out_ap_vld;
reg sysarrayC_36_out_ap_vld;
reg sysarrayC_35_out_ap_vld;
reg sysarrayC_34_out_ap_vld;
reg sysarrayC_33_out_ap_vld;
reg sysarrayC_32_out_ap_vld;
reg sysarrayC_31_out_ap_vld;
reg sysarrayC_30_out_ap_vld;
reg sysarrayC_29_out_ap_vld;
reg sysarrayC_28_out_ap_vld;
reg sysarrayC_27_out_ap_vld;
reg sysarrayC_26_out_ap_vld;
reg sysarrayC_25_out_ap_vld;
reg sysarrayC_24_out_ap_vld;
reg sysarrayC_23_out_ap_vld;
reg sysarrayC_22_out_ap_vld;
reg sysarrayC_21_out_ap_vld;
reg sysarrayC_20_out_ap_vld;
reg sysarrayC_19_out_ap_vld;
reg sysarrayC_18_out_ap_vld;
reg sysarrayC_17_out_ap_vld;
reg sysarrayC_16_out_ap_vld;
reg sysarrayC_15_out_ap_vld;
reg sysarrayC_14_out_ap_vld;
reg sysarrayC_13_out_ap_vld;
reg sysarrayC_12_out_ap_vld;
reg sysarrayC_11_out_ap_vld;
reg sysarrayC_10_out_ap_vld;
reg sysarrayC_9_out_ap_vld;
reg sysarrayC_8_out_ap_vld;
reg sysarrayC_7_out_ap_vld;
reg sysarrayC_6_out_ap_vld;
reg sysarrayC_5_out_ap_vld;
reg sysarrayC_4_out_ap_vld;
reg sysarrayC_3_out_ap_vld;
reg sysarrayC_2_out_ap_vld;
reg sysarrayC_1_out_ap_vld;
reg sysarrayC_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] exitcond110570_fu_886_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [6:0] empty_fu_170;
wire   [6:0] empty_100_fu_892_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_p_load;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

multiplier_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_start_int == 1'b1) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((exitcond110570_fu_886_p2 == 1'd0)) begin
            empty_fu_170 <= empty_100_fu_892_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            empty_fu_170 <= 7'd0;
        end
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_p_load = 7'd0;
    end else begin
        ap_sig_allocacmp_p_load = empty_fu_170;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_10_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_11_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_12_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_13_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_14_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_15_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_16_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_17_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_18_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_19_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_19_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_1_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_20_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_20_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_21_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_22_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_22_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_23_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_23_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_24_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_24_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_25_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_25_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_26_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_26_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_27_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_27_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_28_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_28_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_29_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_29_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_2_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_30_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_30_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_31_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_31_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_32_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_32_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_33_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_33_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_34_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_34_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_35_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_35_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_36_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_36_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_37_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_37_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_38_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_38_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_39_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_39_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_3_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_40_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_40_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_41_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_41_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_42_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_42_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_43_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_43_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_44_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_44_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_45_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_45_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_46_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_46_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_47_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_47_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_48_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_48_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_49_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_49_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_4_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_50_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_50_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_51_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_51_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_52_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_52_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_53_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_53_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_54_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_54_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_55_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_55_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_56_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_56_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_57_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_57_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_58_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_58_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_59_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_59_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_5_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_60_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_60_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_61_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_61_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_62_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_62_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_63_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_63_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_6_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_7_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_8_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_9_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110570_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayC_out_ap_vld = 1'b1;
    end else begin
        sysarrayC_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign empty_100_fu_892_p2 = (ap_sig_allocacmp_p_load + 7'd1);

assign exitcond110570_fu_886_p2 = ((ap_sig_allocacmp_p_load == 7'd64) ? 1'b1 : 1'b0);

assign sysarrayC_10_out = 32'd0;

assign sysarrayC_11_out = 32'd0;

assign sysarrayC_12_out = 32'd0;

assign sysarrayC_13_out = 32'd0;

assign sysarrayC_14_out = 32'd0;

assign sysarrayC_15_out = 32'd0;

assign sysarrayC_16_out = 32'd0;

assign sysarrayC_17_out = 32'd0;

assign sysarrayC_18_out = 32'd0;

assign sysarrayC_19_out = 32'd0;

assign sysarrayC_1_out = 32'd0;

assign sysarrayC_20_out = 32'd0;

assign sysarrayC_21_out = 32'd0;

assign sysarrayC_22_out = 32'd0;

assign sysarrayC_23_out = 32'd0;

assign sysarrayC_24_out = 32'd0;

assign sysarrayC_25_out = 32'd0;

assign sysarrayC_26_out = 32'd0;

assign sysarrayC_27_out = 32'd0;

assign sysarrayC_28_out = 32'd0;

assign sysarrayC_29_out = 32'd0;

assign sysarrayC_2_out = 32'd0;

assign sysarrayC_30_out = 32'd0;

assign sysarrayC_31_out = 32'd0;

assign sysarrayC_32_out = 32'd0;

assign sysarrayC_33_out = 32'd0;

assign sysarrayC_34_out = 32'd0;

assign sysarrayC_35_out = 32'd0;

assign sysarrayC_36_out = 32'd0;

assign sysarrayC_37_out = 32'd0;

assign sysarrayC_38_out = 32'd0;

assign sysarrayC_39_out = 32'd0;

assign sysarrayC_3_out = 32'd0;

assign sysarrayC_40_out = 32'd0;

assign sysarrayC_41_out = 32'd0;

assign sysarrayC_42_out = 32'd0;

assign sysarrayC_43_out = 32'd0;

assign sysarrayC_44_out = 32'd0;

assign sysarrayC_45_out = 32'd0;

assign sysarrayC_46_out = 32'd0;

assign sysarrayC_47_out = 32'd0;

assign sysarrayC_48_out = 32'd0;

assign sysarrayC_49_out = 32'd0;

assign sysarrayC_4_out = 32'd0;

assign sysarrayC_50_out = 32'd0;

assign sysarrayC_51_out = 32'd0;

assign sysarrayC_52_out = 32'd0;

assign sysarrayC_53_out = 32'd0;

assign sysarrayC_54_out = 32'd0;

assign sysarrayC_55_out = 32'd0;

assign sysarrayC_56_out = 32'd0;

assign sysarrayC_57_out = 32'd0;

assign sysarrayC_58_out = 32'd0;

assign sysarrayC_59_out = 32'd0;

assign sysarrayC_5_out = 32'd0;

assign sysarrayC_60_out = 32'd0;

assign sysarrayC_61_out = 32'd0;

assign sysarrayC_62_out = 32'd0;

assign sysarrayC_63_out = 32'd0;

assign sysarrayC_6_out = 32'd0;

assign sysarrayC_7_out = 32'd0;

assign sysarrayC_8_out = 32'd0;

assign sysarrayC_9_out = 32'd0;

assign sysarrayC_out = 32'd0;

endmodule //multiplier_multiplier_Pipeline_6
