// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module multiplier_multiplier_Pipeline_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sysarrayB_rb_63_out,
        sysarrayB_rb_63_out_ap_vld,
        sysarrayB_rb_62_out,
        sysarrayB_rb_62_out_ap_vld,
        sysarrayB_rb_61_out,
        sysarrayB_rb_61_out_ap_vld,
        sysarrayB_rb_60_out,
        sysarrayB_rb_60_out_ap_vld,
        sysarrayB_rb_59_out,
        sysarrayB_rb_59_out_ap_vld,
        sysarrayB_rb_58_out,
        sysarrayB_rb_58_out_ap_vld,
        sysarrayB_rb_57_out,
        sysarrayB_rb_57_out_ap_vld,
        sysarrayB_rb_56_out,
        sysarrayB_rb_56_out_ap_vld,
        sysarrayB_rb_55_out,
        sysarrayB_rb_55_out_ap_vld,
        sysarrayB_rb_54_out,
        sysarrayB_rb_54_out_ap_vld,
        sysarrayB_rb_53_out,
        sysarrayB_rb_53_out_ap_vld,
        sysarrayB_rb_52_out,
        sysarrayB_rb_52_out_ap_vld,
        sysarrayB_rb_51_out,
        sysarrayB_rb_51_out_ap_vld,
        sysarrayB_rb_50_out,
        sysarrayB_rb_50_out_ap_vld,
        sysarrayB_rb_49_out,
        sysarrayB_rb_49_out_ap_vld,
        sysarrayB_rb_48_out,
        sysarrayB_rb_48_out_ap_vld,
        sysarrayB_rb_47_out,
        sysarrayB_rb_47_out_ap_vld,
        sysarrayB_rb_46_out,
        sysarrayB_rb_46_out_ap_vld,
        sysarrayB_rb_45_out,
        sysarrayB_rb_45_out_ap_vld,
        sysarrayB_rb_44_out,
        sysarrayB_rb_44_out_ap_vld,
        sysarrayB_rb_43_out,
        sysarrayB_rb_43_out_ap_vld,
        sysarrayB_rb_42_out,
        sysarrayB_rb_42_out_ap_vld,
        sysarrayB_rb_41_out,
        sysarrayB_rb_41_out_ap_vld,
        sysarrayB_rb_40_out,
        sysarrayB_rb_40_out_ap_vld,
        sysarrayB_rb_39_out,
        sysarrayB_rb_39_out_ap_vld,
        sysarrayB_rb_38_out,
        sysarrayB_rb_38_out_ap_vld,
        sysarrayB_rb_37_out,
        sysarrayB_rb_37_out_ap_vld,
        sysarrayB_rb_36_out,
        sysarrayB_rb_36_out_ap_vld,
        sysarrayB_rb_35_out,
        sysarrayB_rb_35_out_ap_vld,
        sysarrayB_rb_34_out,
        sysarrayB_rb_34_out_ap_vld,
        sysarrayB_rb_33_out,
        sysarrayB_rb_33_out_ap_vld,
        sysarrayB_rb_32_out,
        sysarrayB_rb_32_out_ap_vld,
        sysarrayB_rb_31_out,
        sysarrayB_rb_31_out_ap_vld,
        sysarrayB_rb_30_out,
        sysarrayB_rb_30_out_ap_vld,
        sysarrayB_rb_29_out,
        sysarrayB_rb_29_out_ap_vld,
        sysarrayB_rb_28_out,
        sysarrayB_rb_28_out_ap_vld,
        sysarrayB_rb_27_out,
        sysarrayB_rb_27_out_ap_vld,
        sysarrayB_rb_26_out,
        sysarrayB_rb_26_out_ap_vld,
        sysarrayB_rb_25_out,
        sysarrayB_rb_25_out_ap_vld,
        sysarrayB_rb_24_out,
        sysarrayB_rb_24_out_ap_vld,
        sysarrayB_rb_23_out,
        sysarrayB_rb_23_out_ap_vld,
        sysarrayB_rb_22_out,
        sysarrayB_rb_22_out_ap_vld,
        sysarrayB_rb_21_out,
        sysarrayB_rb_21_out_ap_vld,
        sysarrayB_rb_20_out,
        sysarrayB_rb_20_out_ap_vld,
        sysarrayB_rb_19_out,
        sysarrayB_rb_19_out_ap_vld,
        sysarrayB_rb_18_out,
        sysarrayB_rb_18_out_ap_vld,
        sysarrayB_rb_17_out,
        sysarrayB_rb_17_out_ap_vld,
        sysarrayB_rb_16_out,
        sysarrayB_rb_16_out_ap_vld,
        sysarrayB_rb_15_out,
        sysarrayB_rb_15_out_ap_vld,
        sysarrayB_rb_14_out,
        sysarrayB_rb_14_out_ap_vld,
        sysarrayB_rb_13_out,
        sysarrayB_rb_13_out_ap_vld,
        sysarrayB_rb_12_out,
        sysarrayB_rb_12_out_ap_vld,
        sysarrayB_rb_11_out,
        sysarrayB_rb_11_out_ap_vld,
        sysarrayB_rb_10_out,
        sysarrayB_rb_10_out_ap_vld,
        sysarrayB_rb_9_out,
        sysarrayB_rb_9_out_ap_vld,
        sysarrayB_rb_8_out,
        sysarrayB_rb_8_out_ap_vld,
        sysarrayB_rb_7_out,
        sysarrayB_rb_7_out_ap_vld,
        sysarrayB_rb_6_out,
        sysarrayB_rb_6_out_ap_vld,
        sysarrayB_rb_5_out,
        sysarrayB_rb_5_out_ap_vld,
        sysarrayB_rb_4_out,
        sysarrayB_rb_4_out_ap_vld,
        sysarrayB_rb_3_out,
        sysarrayB_rb_3_out_ap_vld,
        sysarrayB_rb_2_out,
        sysarrayB_rb_2_out_ap_vld,
        sysarrayB_rb_1_out,
        sysarrayB_rb_1_out_ap_vld,
        sysarrayB_rb_out,
        sysarrayB_rb_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [31:0] sysarrayB_rb_63_out;
output   sysarrayB_rb_63_out_ap_vld;
output  [31:0] sysarrayB_rb_62_out;
output   sysarrayB_rb_62_out_ap_vld;
output  [31:0] sysarrayB_rb_61_out;
output   sysarrayB_rb_61_out_ap_vld;
output  [31:0] sysarrayB_rb_60_out;
output   sysarrayB_rb_60_out_ap_vld;
output  [31:0] sysarrayB_rb_59_out;
output   sysarrayB_rb_59_out_ap_vld;
output  [31:0] sysarrayB_rb_58_out;
output   sysarrayB_rb_58_out_ap_vld;
output  [31:0] sysarrayB_rb_57_out;
output   sysarrayB_rb_57_out_ap_vld;
output  [31:0] sysarrayB_rb_56_out;
output   sysarrayB_rb_56_out_ap_vld;
output  [31:0] sysarrayB_rb_55_out;
output   sysarrayB_rb_55_out_ap_vld;
output  [31:0] sysarrayB_rb_54_out;
output   sysarrayB_rb_54_out_ap_vld;
output  [31:0] sysarrayB_rb_53_out;
output   sysarrayB_rb_53_out_ap_vld;
output  [31:0] sysarrayB_rb_52_out;
output   sysarrayB_rb_52_out_ap_vld;
output  [31:0] sysarrayB_rb_51_out;
output   sysarrayB_rb_51_out_ap_vld;
output  [31:0] sysarrayB_rb_50_out;
output   sysarrayB_rb_50_out_ap_vld;
output  [31:0] sysarrayB_rb_49_out;
output   sysarrayB_rb_49_out_ap_vld;
output  [31:0] sysarrayB_rb_48_out;
output   sysarrayB_rb_48_out_ap_vld;
output  [31:0] sysarrayB_rb_47_out;
output   sysarrayB_rb_47_out_ap_vld;
output  [31:0] sysarrayB_rb_46_out;
output   sysarrayB_rb_46_out_ap_vld;
output  [31:0] sysarrayB_rb_45_out;
output   sysarrayB_rb_45_out_ap_vld;
output  [31:0] sysarrayB_rb_44_out;
output   sysarrayB_rb_44_out_ap_vld;
output  [31:0] sysarrayB_rb_43_out;
output   sysarrayB_rb_43_out_ap_vld;
output  [31:0] sysarrayB_rb_42_out;
output   sysarrayB_rb_42_out_ap_vld;
output  [31:0] sysarrayB_rb_41_out;
output   sysarrayB_rb_41_out_ap_vld;
output  [31:0] sysarrayB_rb_40_out;
output   sysarrayB_rb_40_out_ap_vld;
output  [31:0] sysarrayB_rb_39_out;
output   sysarrayB_rb_39_out_ap_vld;
output  [31:0] sysarrayB_rb_38_out;
output   sysarrayB_rb_38_out_ap_vld;
output  [31:0] sysarrayB_rb_37_out;
output   sysarrayB_rb_37_out_ap_vld;
output  [31:0] sysarrayB_rb_36_out;
output   sysarrayB_rb_36_out_ap_vld;
output  [31:0] sysarrayB_rb_35_out;
output   sysarrayB_rb_35_out_ap_vld;
output  [31:0] sysarrayB_rb_34_out;
output   sysarrayB_rb_34_out_ap_vld;
output  [31:0] sysarrayB_rb_33_out;
output   sysarrayB_rb_33_out_ap_vld;
output  [31:0] sysarrayB_rb_32_out;
output   sysarrayB_rb_32_out_ap_vld;
output  [31:0] sysarrayB_rb_31_out;
output   sysarrayB_rb_31_out_ap_vld;
output  [31:0] sysarrayB_rb_30_out;
output   sysarrayB_rb_30_out_ap_vld;
output  [31:0] sysarrayB_rb_29_out;
output   sysarrayB_rb_29_out_ap_vld;
output  [31:0] sysarrayB_rb_28_out;
output   sysarrayB_rb_28_out_ap_vld;
output  [31:0] sysarrayB_rb_27_out;
output   sysarrayB_rb_27_out_ap_vld;
output  [31:0] sysarrayB_rb_26_out;
output   sysarrayB_rb_26_out_ap_vld;
output  [31:0] sysarrayB_rb_25_out;
output   sysarrayB_rb_25_out_ap_vld;
output  [31:0] sysarrayB_rb_24_out;
output   sysarrayB_rb_24_out_ap_vld;
output  [31:0] sysarrayB_rb_23_out;
output   sysarrayB_rb_23_out_ap_vld;
output  [31:0] sysarrayB_rb_22_out;
output   sysarrayB_rb_22_out_ap_vld;
output  [31:0] sysarrayB_rb_21_out;
output   sysarrayB_rb_21_out_ap_vld;
output  [31:0] sysarrayB_rb_20_out;
output   sysarrayB_rb_20_out_ap_vld;
output  [31:0] sysarrayB_rb_19_out;
output   sysarrayB_rb_19_out_ap_vld;
output  [31:0] sysarrayB_rb_18_out;
output   sysarrayB_rb_18_out_ap_vld;
output  [31:0] sysarrayB_rb_17_out;
output   sysarrayB_rb_17_out_ap_vld;
output  [31:0] sysarrayB_rb_16_out;
output   sysarrayB_rb_16_out_ap_vld;
output  [31:0] sysarrayB_rb_15_out;
output   sysarrayB_rb_15_out_ap_vld;
output  [31:0] sysarrayB_rb_14_out;
output   sysarrayB_rb_14_out_ap_vld;
output  [31:0] sysarrayB_rb_13_out;
output   sysarrayB_rb_13_out_ap_vld;
output  [31:0] sysarrayB_rb_12_out;
output   sysarrayB_rb_12_out_ap_vld;
output  [31:0] sysarrayB_rb_11_out;
output   sysarrayB_rb_11_out_ap_vld;
output  [31:0] sysarrayB_rb_10_out;
output   sysarrayB_rb_10_out_ap_vld;
output  [31:0] sysarrayB_rb_9_out;
output   sysarrayB_rb_9_out_ap_vld;
output  [31:0] sysarrayB_rb_8_out;
output   sysarrayB_rb_8_out_ap_vld;
output  [31:0] sysarrayB_rb_7_out;
output   sysarrayB_rb_7_out_ap_vld;
output  [31:0] sysarrayB_rb_6_out;
output   sysarrayB_rb_6_out_ap_vld;
output  [31:0] sysarrayB_rb_5_out;
output   sysarrayB_rb_5_out_ap_vld;
output  [31:0] sysarrayB_rb_4_out;
output   sysarrayB_rb_4_out_ap_vld;
output  [31:0] sysarrayB_rb_3_out;
output   sysarrayB_rb_3_out_ap_vld;
output  [31:0] sysarrayB_rb_2_out;
output   sysarrayB_rb_2_out_ap_vld;
output  [31:0] sysarrayB_rb_1_out;
output   sysarrayB_rb_1_out_ap_vld;
output  [31:0] sysarrayB_rb_out;
output   sysarrayB_rb_out_ap_vld;

reg ap_idle;
reg sysarrayB_rb_63_out_ap_vld;
reg sysarrayB_rb_62_out_ap_vld;
reg sysarrayB_rb_61_out_ap_vld;
reg sysarrayB_rb_60_out_ap_vld;
reg sysarrayB_rb_59_out_ap_vld;
reg sysarrayB_rb_58_out_ap_vld;
reg sysarrayB_rb_57_out_ap_vld;
reg sysarrayB_rb_56_out_ap_vld;
reg sysarrayB_rb_55_out_ap_vld;
reg sysarrayB_rb_54_out_ap_vld;
reg sysarrayB_rb_53_out_ap_vld;
reg sysarrayB_rb_52_out_ap_vld;
reg sysarrayB_rb_51_out_ap_vld;
reg sysarrayB_rb_50_out_ap_vld;
reg sysarrayB_rb_49_out_ap_vld;
reg sysarrayB_rb_48_out_ap_vld;
reg sysarrayB_rb_47_out_ap_vld;
reg sysarrayB_rb_46_out_ap_vld;
reg sysarrayB_rb_45_out_ap_vld;
reg sysarrayB_rb_44_out_ap_vld;
reg sysarrayB_rb_43_out_ap_vld;
reg sysarrayB_rb_42_out_ap_vld;
reg sysarrayB_rb_41_out_ap_vld;
reg sysarrayB_rb_40_out_ap_vld;
reg sysarrayB_rb_39_out_ap_vld;
reg sysarrayB_rb_38_out_ap_vld;
reg sysarrayB_rb_37_out_ap_vld;
reg sysarrayB_rb_36_out_ap_vld;
reg sysarrayB_rb_35_out_ap_vld;
reg sysarrayB_rb_34_out_ap_vld;
reg sysarrayB_rb_33_out_ap_vld;
reg sysarrayB_rb_32_out_ap_vld;
reg sysarrayB_rb_31_out_ap_vld;
reg sysarrayB_rb_30_out_ap_vld;
reg sysarrayB_rb_29_out_ap_vld;
reg sysarrayB_rb_28_out_ap_vld;
reg sysarrayB_rb_27_out_ap_vld;
reg sysarrayB_rb_26_out_ap_vld;
reg sysarrayB_rb_25_out_ap_vld;
reg sysarrayB_rb_24_out_ap_vld;
reg sysarrayB_rb_23_out_ap_vld;
reg sysarrayB_rb_22_out_ap_vld;
reg sysarrayB_rb_21_out_ap_vld;
reg sysarrayB_rb_20_out_ap_vld;
reg sysarrayB_rb_19_out_ap_vld;
reg sysarrayB_rb_18_out_ap_vld;
reg sysarrayB_rb_17_out_ap_vld;
reg sysarrayB_rb_16_out_ap_vld;
reg sysarrayB_rb_15_out_ap_vld;
reg sysarrayB_rb_14_out_ap_vld;
reg sysarrayB_rb_13_out_ap_vld;
reg sysarrayB_rb_12_out_ap_vld;
reg sysarrayB_rb_11_out_ap_vld;
reg sysarrayB_rb_10_out_ap_vld;
reg sysarrayB_rb_9_out_ap_vld;
reg sysarrayB_rb_8_out_ap_vld;
reg sysarrayB_rb_7_out_ap_vld;
reg sysarrayB_rb_6_out_ap_vld;
reg sysarrayB_rb_5_out_ap_vld;
reg sysarrayB_rb_4_out_ap_vld;
reg sysarrayB_rb_3_out_ap_vld;
reg sysarrayB_rb_2_out_ap_vld;
reg sysarrayB_rb_1_out_ap_vld;
reg sysarrayB_rb_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] exitcond110671_fu_886_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [6:0] empty_fu_170;
wire   [6:0] empty_103_fu_892_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_p_load;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

multiplier_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_start_int == 1'b1) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((exitcond110671_fu_886_p2 == 1'd0)) begin
            empty_fu_170 <= empty_103_fu_892_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            empty_fu_170 <= 7'd0;
        end
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_p_load = 7'd0;
    end else begin
        ap_sig_allocacmp_p_load = empty_fu_170;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_10_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_10_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_11_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_11_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_12_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_12_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_13_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_13_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_14_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_14_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_15_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_15_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_16_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_16_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_17_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_17_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_18_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_19_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_19_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_1_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_20_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_20_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_21_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_21_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_22_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_22_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_23_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_23_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_24_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_24_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_25_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_25_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_26_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_26_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_27_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_27_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_28_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_28_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_29_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_29_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_2_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_30_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_30_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_31_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_31_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_32_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_32_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_33_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_33_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_34_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_34_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_35_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_35_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_36_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_36_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_37_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_37_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_38_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_38_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_39_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_39_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_3_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_40_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_40_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_41_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_41_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_42_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_42_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_43_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_43_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_44_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_44_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_45_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_45_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_46_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_46_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_47_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_47_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_48_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_48_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_49_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_49_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_4_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_50_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_50_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_51_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_51_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_52_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_52_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_53_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_53_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_54_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_54_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_55_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_55_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_56_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_56_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_57_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_57_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_58_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_58_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_59_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_59_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_5_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_60_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_60_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_61_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_61_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_62_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_62_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_63_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_63_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_6_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_7_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_8_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_8_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_9_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_9_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (exitcond110671_fu_886_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        sysarrayB_rb_out_ap_vld = 1'b1;
    end else begin
        sysarrayB_rb_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign empty_103_fu_892_p2 = (ap_sig_allocacmp_p_load + 7'd1);

assign exitcond110671_fu_886_p2 = ((ap_sig_allocacmp_p_load == 7'd64) ? 1'b1 : 1'b0);

assign sysarrayB_rb_10_out = 32'd0;

assign sysarrayB_rb_11_out = 32'd0;

assign sysarrayB_rb_12_out = 32'd0;

assign sysarrayB_rb_13_out = 32'd0;

assign sysarrayB_rb_14_out = 32'd0;

assign sysarrayB_rb_15_out = 32'd0;

assign sysarrayB_rb_16_out = 32'd0;

assign sysarrayB_rb_17_out = 32'd0;

assign sysarrayB_rb_18_out = 32'd0;

assign sysarrayB_rb_19_out = 32'd0;

assign sysarrayB_rb_1_out = 32'd0;

assign sysarrayB_rb_20_out = 32'd0;

assign sysarrayB_rb_21_out = 32'd0;

assign sysarrayB_rb_22_out = 32'd0;

assign sysarrayB_rb_23_out = 32'd0;

assign sysarrayB_rb_24_out = 32'd0;

assign sysarrayB_rb_25_out = 32'd0;

assign sysarrayB_rb_26_out = 32'd0;

assign sysarrayB_rb_27_out = 32'd0;

assign sysarrayB_rb_28_out = 32'd0;

assign sysarrayB_rb_29_out = 32'd0;

assign sysarrayB_rb_2_out = 32'd0;

assign sysarrayB_rb_30_out = 32'd0;

assign sysarrayB_rb_31_out = 32'd0;

assign sysarrayB_rb_32_out = 32'd0;

assign sysarrayB_rb_33_out = 32'd0;

assign sysarrayB_rb_34_out = 32'd0;

assign sysarrayB_rb_35_out = 32'd0;

assign sysarrayB_rb_36_out = 32'd0;

assign sysarrayB_rb_37_out = 32'd0;

assign sysarrayB_rb_38_out = 32'd0;

assign sysarrayB_rb_39_out = 32'd0;

assign sysarrayB_rb_3_out = 32'd0;

assign sysarrayB_rb_40_out = 32'd0;

assign sysarrayB_rb_41_out = 32'd0;

assign sysarrayB_rb_42_out = 32'd0;

assign sysarrayB_rb_43_out = 32'd0;

assign sysarrayB_rb_44_out = 32'd0;

assign sysarrayB_rb_45_out = 32'd0;

assign sysarrayB_rb_46_out = 32'd0;

assign sysarrayB_rb_47_out = 32'd0;

assign sysarrayB_rb_48_out = 32'd0;

assign sysarrayB_rb_49_out = 32'd0;

assign sysarrayB_rb_4_out = 32'd0;

assign sysarrayB_rb_50_out = 32'd0;

assign sysarrayB_rb_51_out = 32'd0;

assign sysarrayB_rb_52_out = 32'd0;

assign sysarrayB_rb_53_out = 32'd0;

assign sysarrayB_rb_54_out = 32'd0;

assign sysarrayB_rb_55_out = 32'd0;

assign sysarrayB_rb_56_out = 32'd0;

assign sysarrayB_rb_57_out = 32'd0;

assign sysarrayB_rb_58_out = 32'd0;

assign sysarrayB_rb_59_out = 32'd0;

assign sysarrayB_rb_5_out = 32'd0;

assign sysarrayB_rb_60_out = 32'd0;

assign sysarrayB_rb_61_out = 32'd0;

assign sysarrayB_rb_62_out = 32'd0;

assign sysarrayB_rb_63_out = 32'd0;

assign sysarrayB_rb_6_out = 32'd0;

assign sysarrayB_rb_7_out = 32'd0;

assign sysarrayB_rb_8_out = 32'd0;

assign sysarrayB_rb_9_out = 32'd0;

assign sysarrayB_rb_out = 32'd0;

endmodule //multiplier_multiplier_Pipeline_5
